// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ArrayLabels = require("bs-platform/lib/js/arrayLabels.js");

var Bullet = {};

var cmp = Caml_obj.caml_compare;

var BulletComparator = Belt_Id.MakeComparable({
      cmp: cmp
    });

function bulletOfString(str) {
  var indicator = str.substring(0, 2);
  var bulletType;
  switch (indicator) {
    case ".-" :
        bulletType = /* Todo */1;
        break;
    case ".." :
        bulletType = /* Item */2;
        break;
    case ".?" :
        bulletType = /* Question */0;
        break;
    default:
      bulletType = /* Item */2;
  }
  var value = str.substring(3, 6);
  return {
          bulletType: bulletType,
          value: value
        };
}

function processBullets(bullets) {
  return Belt_List.map(bullets, bulletOfString);
}

var filename = "test.md";

var fileContents = Fs.readFileSync(filename, "utf8");

var lines = fileContents.split("\n");

var bulletsList = Belt_List.map(ArrayLabels.to_list(lines), bulletOfString);

Belt_List.forEach(bulletsList, (function (a) {
        console.log(a);
        
      }));

exports.Bullet = Bullet;
exports.BulletComparator = BulletComparator;
exports.bulletOfString = bulletOfString;
exports.processBullets = processBullets;
exports.filename = filename;
exports.fileContents = fileContents;
exports.lines = lines;
exports.bulletsList = bulletsList;
/* BulletComparator Not a pure module */
